### ISSUE TITLE
Show links to table as `Table 1`, not the full caption

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-camera-trap-guide#11]
In https://docs.gbif-uat.org/camera-trap-guide/en/#media-files we refer to a table as `<<table-exif>>`

https://github.com/gbif/doc-camera-trap-guide/blob/48daf4773142fd6f3fd2f8a3b0c1d0506a43e020/300.en.adoc?plain=1#L172-L180

- Good: the table gets automatically assigned a number
- Good: the table has a caption
- Bad: the reference to the table shows the whole caption of the table, rather than `Table 1`

<img width="960" alt="Screenshot 2023-06-13 at 17 35 53" src="https://github.com/gbif/doc-camera-trap-guide/assets/600993/7595a120-fc4c-4c70-b041-3a5a6396bbcb">

The same syntax is used in the georeferencing guide and there it [shows as `Table 1` in the text](https://docs.gbif.org/georeferencing-best-practices/1.0/en/#uncertainty-in-paper-map-measurements). @MattBlissett How can we enable this?

**Comment by MattBlissett** [comment]
That document defaults to `:xrefstyle: short` so many other links are e.g. "See §2.3.1" rather than "See Georeferencing".  That attribute is set in index.en.adoc.

Alternatively, you can use the short reference style only for tables, with `xref:table-exif[xrefstyle="short"]` instead of `<<table-exif>>`. (`xref:table-exif[]` is equivalent to `<<table-exif>>`.)

**Comment by peterdesmet** [comment]
Thanks, I have set the global option.
