### ISSUE TITLE
marine example

### ISSUE THREAD

**Issue by sformel-usgs** [gbif/doc-camera-trap-guide#36]
I know we're still discussing depth as a possible term for the standard, so this is a bit of a placeholder.  I think that adding marine mentions (e.g. fish in section 2.2, and WoRMS in Table 9 / section 3.5.5) will help buy-in from the marine community. If/when it's appropriate, I'd be happy to help develop a marine example dataset. 

Tagging @sachitrajbhandari, who may also have an interest.

**Comment by ben-norton** [comment]
I completely agree. There are hidden challenges in doing so that will require additional sections. Fish don't trigger infared. Underwater traps require long recorded videos. So they aren't camera traps in the traditional sense. Further,  many of the deployment properties aren't applicable to videos. Th data processing workglow is different as well. It's not complicated, but to provide the necessary guidance requires additional sections. 
Processing workflow rxample. 
Videos are recorded in 2 hour blocks 4 tines per day for two weeks. After diwnloading the data from the camera, each video is split into individual frames. At ~72 fps, that's a lot of frames. An acceptable generalization is to extract one frame per second or every 72nd frame in the sequence. Then you could run machine learning to filter blanks and so on.
There are a lot of hidden details that are a departure from the infared terrestrial-based devices (since videos are captured at set intervals, does that affect the deployment definition? How does it affect modeling? Can the frames be merged with terrestrial photos?)

**Comment by ben-norton** [comment]
I completely agree. There are hidden challenges in doing so that will require additional sections. Fish don't trigger infared. Underwater traps require long recorded videos. So they aren't camera traps in the traditional sense. Further,  many of the deployment properties aren't applicable to videos. Th data processing workglow is different as well. It's not complicated, but to provide the necessary guidance requires additional sections. 
Processing workflow rxample. 
Videos are recorded in 2 hour blocks 4 tines per day for two weeks. After diwnloading the data from the camera, each video is split into individual frames. At ~72 fps, that's a lot of frames. An acceptable generalization is to extract one frame per second or every 72nd frame in the sequence. Then you could run machine learning to filter blanks and so on.
There are a lot of hidden details that are a departure from the infared terrestrial-based devices (since videos are captured at set intervals, does that affect the deployment definition? How does it affect modeling? Can the frames be merged with terrestrial photos?)

**Comment by sformel-usgs** [comment]
@ben-norton there is a marine dataset I have in mind to test the CamTrap DP standard, I just haven't carved out any time to really get into it yet.  It is a set of baited cameras deployed on some dock pilings.  In many ways it is a traditional Camera Trap.  Do you have a dataset in that you could test out? Between the two of us, maybe we could rough out a marine example and the additional sections that might be needed.

**Comment by sformel-usgs** [comment]
I hadn't realized @sachitrajbhandari has already explored CamTrap DP for a marine dataset as part of an OBIS Project Team. Just adding the link in case, it is useful starting material for a marine example: https://github.com/obisau/camtrap

**Comment by peterdesmet** [comment]
Update: I have now included **camera depth** in the guide:

- It has a glossary term: https://docs.gbif-uat.org/camera-trap-guide/en/#camera-depth
- Both cameraHeight and cameraDepth have suggested mappings to Darwin Core:
  - https://docs.gbif-uat.org/camera-trap-guide/en/#section-minimumdepthinmeters-maximumdepthinmeters
  - https://docs.gbif-uat.org/camera-trap-guide/en/#section-minimumdistanceabovesurfaceinmeters-maximumdistanceabovesurfaceinmeters

**Comment by peterdesmet** [comment]
- Marine environment is now mentioned in [2.1](https://docs.gbif-uat.org/camera-trap-guide/en/#section-what-are-camera-traps)
- Fish are now mentioned in [2.2](https://docs.gbif-uat.org/camera-trap-guide/en/#section-why-are-camera-traps-used)
- WoRMS is now mentioned in [Table 10](https://docs.gbif-uat.org/camera-trap-guide/en/#table-taxon-reference-sources)
- CameraDepth is now mentioned in the glossary and Darwin Core mapping (see comment above)

@sformel-usgs I think that closes the action items for the guide, so I'll close this issue. Further exploration of Camtrap DP for marine datasets is always welcome though.
